# Site settings
title: 玖贰壬申年
SEOTitle: 壬申的博客 | Jeremy Blog
header-img: img/blog-desk.jpg
email: jinzhejx@gmail.com
description: "Write the Code,Change the World."
keyword: "玖贰, 壬申年, Jeremy, Android, 运动, 户外"
url: "http://jinzhe1992.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "每天记日记，写出上下10000年"
sidebar-avatar: /img/blog-avatar_myself.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     jinzhe1992
instagram_username:     jxjinzhe
github_username:    jinzhe1992
facebook_username:  Zhe King
twitter_username:   jimzhe




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: jinzhe1992




# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-106867672-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "京东",
        href: "https://www.jd.com/"
    },{
        title: "小米",
        href: "https://www.mi.com/"
    },{
        title: "Google",
        href: "https://www.google.com.hk"
    },{
        title: "电影下载",
        href: "http://www.6vhao.tv/"
    }
]
